### PR TITLE
add caution regarding append & prepend immutability

### PR DESCRIPTION
**Pull request by instabledesign**

### CODE REVIEW

**Comment by instabledesign** [comment]
we have 2 solution about append/prepend
1️⃣ stack = stack.Append(...) (stack immutable, same as stack = append(stack, ...)) 
2️⃣ stack.Append(...) stack mutable for this method and we can imagine create 
`AppendIf(bool, ...)`
after reflexion i think more option 2️⃣ because method really add value and not only forward to native append function

**Comment by pimousse1099** [comment]
1️⃣ is a more idiomatic way 

2️⃣ is a more flexible/extendable way

**Review by pimousse1099 — APPROVED** [review]

**Comment by pimousse1099** [comment]
Appendif might conflict with enable or skip middlewares

**Comment by instabledesign** [comment]
close in favor of https://github.com/gol4ng/httpware/pull/31

**Pull request closed without merging**
