### PR TITLE
Add context on Authenticate func

### PR DESCRIPTION
**Pull request by instabledesign**
## ⚠️ BC Break

```
type Authenticator interface {
    func Authenticate(Credential) (Credential, error)
}
type AuthenticatorFunc func(Credential) (Credential, error)
```
BECOME
```
type Authenticator interface {
    func Authenticate(context.Context, Credential) (Credential, error)
}
type AuthenticatorFunc func(context.Context, Credential) (Credential, error)
```

### CODE REVIEW

**Review by qneyrat — DISMISSED** [review]

**Review by pimousse1099 — DISMISSED** [review]
Be careful to add a `BC Break` warning after merging it 👍

**Comment by instabledesign** [comment]
we can merge BC break on master branch, but we need to create the appropriate release version

**Comment by pimousse1099** [comment]
> we can merge BC break on master branch, but we need to create the appropriate release version

yep definitely

**Comment by instabledesign** [comment]
It seems the best way is to create a v4 branch based on master (update all the import .../v4) and point all new commit/BC break directly on this branch before release the all things

**Pull request merged**
